### ISSUE TITLE
Problem in view permission after using module

### ISSUE THREAD

**Issue by foreverXZC** [rahulkhengare/terraform-azurerm-webapp#1]
I have used your module to deploy a webapp on Azure. I think your job was really fascinating because it actually provides a valid webapp URL. However, I found that when I open this URL, the website shows "You do not have permission to view this directory or page." Even if I downloaded the whole zip file from GitHub and run it, such problem still occurs.
After I compare your source code with tutorial in "https://docs.microsoft.com/en-us/azure/terraform/terraform-slot-walkthru", I tried to remove one line in resource "azurerm_app_service" "webapp", that is, site_config = "${var.site_config}". Finally, the website indicates "Your App Service app is up and running." As a result, I can deploy any web applications on it, for instance, "Hello World!" in index.html.
I am curious about whether it's my fault in usage or I understand site_config incorrectly. I am looking forward to hearing from you. Thanks a lot!

**Comment by rahulkhengare** [comment]
Thanks @foreverXZC for trying the module. 

A site_config feature is not working currently even in the terraform azurerm_app_service resource for .NET kind of webapp. If I pass any parameters in site_config for .NET webapp then it is giving error.

Currently, site_config setting is [] for .NET based webapp. If we want to use JAVA based webapp then provide the configuration mentioned in readme file.

I will fix this once it is reflected in the terraform resource.
Feel free to contribute to this module.

**Comment by foreverXZC** [comment]
Thanks for reply. It really makes sense. Looking forward to the next version.

**Comment by rahulkhengare** [comment]
Cl
